"""
Desktop panel for the Discord EDR — Discord-style dark theme.

Does not depend on discord.py: it reads directly from the SQLite database
generated by the bot (data/edr.db) and manages the rules file
(data/rules.json) through the same RuleEngine class the bot uses. The bot
can be running and this panel open at the same time with no conflict
(SQLite supports concurrent reads).

Moderation actions (ban, kick, warn) are not executed directly by this
panel: they're queued in the `pending_actions` table via queue_action(),
and it's the bot -which holds the live Discord connection and
permissions- that executes them on its next polling cycle.

Also starts/stops the bot itself (bot_runner.start_bot / stop_bot) on a
background thread, so opening the panel is enough to bring the whole
system up.

Run from the project root:
    python -m desktop_app.app
"""
import os
import sys
import csv

# Allows importing the "bot" package even when running from another folder.
# This must happen BEFORE any "from bot..." import.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tkinter as tk
from tkinter import ttk, messagebox, simpledialog, filedialog

import matplotlib
matplotlib.use("TkAgg")  # backend embebible en Tkinter, sin ventana propia
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from bot.db.database import (
    init_db, fetch_alerts, fetch_events, fetch_members,
    count_alerts_by_severity, top_active_users, queue_action,
    fetch_actions_for_user, fetch_alerts_by_day, fetch_rule_ranking,
    fetch_top_alerting_users,
)
from bot.rule_engine import RuleEngine
from desktop_app import theme, bot_runner

REFRESH_MS = 3000  # how often the view auto-refreshes (ms)
BOT_STATUS_MS = 2000  # how often the bot connection status label is updated (ms)

EVENT_TYPES = [
    "todos", "message_create", "message_edit", "message_delete",
    "member_join", "member_leave", "member_ban", "member_update",
]


class EDRDesktopApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Discord EDR — Panel de control")
        self.geometry("1150x760")
        self.minsize(900, 600)
        self.protocol("WM_DELETE_WINDOW", self._on_close)

        init_db()
        self.rule_engine = RuleEngine()

        self._build_ui()
        self._start_bot()
        self._refresh_all()
        self.after(REFRESH_MS, self._auto_refresh)
        self.after(BOT_STATUS_MS, self._update_bot_status)

    # ------------------------------------------------------------------
    # Bot lifecycle (bot_runner starts/stops the actual Discord bot on a
    # background thread — the README/run_app.py docstring already promise
    # this happens automatically when the panel opens, this is what wires
    # it up)
    # ------------------------------------------------------------------
    def _start_bot(self):
        ok, message = bot_runner.start_bot()
        self.bot_status_var.set(message if ok else f"Bot: {message}")

    def _update_bot_status(self):
        self.bot_status_var.set(f"Bot: {bot_runner.status_text()}")
        self.after(BOT_STATUS_MS, self._update_bot_status)

    def _on_close(self):
        if bot_runner.is_running():
            bot_runner.stop_bot()
        self.destroy()

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------
    def _build_ui(self):
        theme.apply_theme(self)

        notebook = ttk.Notebook(self)
        notebook.pack(fill="both", expand=True)

        self.tab_dashboard = ttk.Frame(notebook)
        self.tab_events = ttk.Frame(notebook)
        self.tab_members = ttk.Frame(notebook)
        self.tab_rules = ttk.Frame(notebook)
        self.tab_analytics = ttk.Frame(notebook)

        notebook.add(self.tab_dashboard, text="📊 Dashboard")
        notebook.add(self.tab_events, text="💬 Eventos")
        notebook.add(self.tab_members, text="👥 Miembros")
        notebook.add(self.tab_rules, text="⚙️ Reglas")
        notebook.add(self.tab_analytics, text="📈 Analítica")

        self._build_dashboard_tab()
        self._build_events_tab()
        self._build_members_tab()
        self._build_rules_tab()
        self._build_analytics_tab()

        # bottom status bar: app status on the left, bot connection status on the right
        bottom = ttk.Frame(self, style="Card.TFrame")
        bottom.pack(fill="x", side="bottom")

        self.status_var = tk.StringVar(value="Listo.")
        ttk.Label(bottom, textvariable=self.status_var, anchor="w",
                  style="StatusBar.TLabel").pack(fill="x", side="left", expand=True)

        self.bot_status_var = tk.StringVar(value="Bot: starting...")
        ttk.Label(bottom, textvariable=self.bot_status_var, anchor="e",
                  style="StatusBar.TLabel").pack(side="right", padx=10)

    def _make_stat_card(self, parent, severity):
        """Dark card with a side color strip matching the severity."""
        outer = ttk.Frame(parent, style="Card.TFrame")
        outer.pack(side="left", padx=(0, 10), fill="y")

        strip = tk.Frame(outer, bg=theme.SEVERITY_COLORS[severity], width=4)
        strip.pack(side="left", fill="y")

        inner = ttk.Frame(outer, style="Card.TFrame", padding=(14, 10))
        inner.pack(side="left", fill="both", expand=True)

        ttk.Label(inner, text=severity.upper(), style="StatLabel.TLabel").pack(anchor="w")
        lbl = ttk.Label(inner, text="0", style="StatNumber.TLabel")
        lbl.pack(anchor="w")
        return lbl

    def _build_dashboard_tab(self):
        top = ttk.Frame(self.tab_dashboard, padding=12)
        top.pack(fill="x")

        self.stat_labels = {}
        for sev in ("critical", "high", "medium", "low"):
            self.stat_labels[sev] = self._make_stat_card(top, sev)

        ttk.Button(top, text="🔄 Refrescar ahora", style="Accent.TButton",
                   command=self._refresh_all).pack(side="right", padx=8)

        ttk.Label(self.tab_dashboard, text="Últimas alertas (selecciona una fila para actuar)",
                  style="Header.TLabel").pack(anchor="w", padx=14, pady=(4, 6))

        columns = ("timestamp", "severity", "rule_name", "username", "description")
        headers = ("Fecha/hora", "Severidad", "Regla", "Usuario", "Descripción")
        self.alerts_tree = ttk.Treeview(self.tab_dashboard, columns=columns, show="headings", height=16)
        for col, head, width in zip(columns, headers, (150, 90, 130, 140, 450)):
            self.alerts_tree.heading(col, text=head)
            self.alerts_tree.column(col, width=width, anchor="w")
        self.alerts_tree.pack(fill="both", expand=True, padx=12, pady=(0, 8))

        theme.tag_configure_zebra(self.alerts_tree)
        for sev, color in theme.SEVERITY_COLORS.items():
            self.alerts_tree.tag_configure(sev, foreground=color)

        # --- Moderation actions on the selected alert ---
        alert_actions = ttk.Frame(self.tab_dashboard, padding=(12, 4, 12, 10))
        alert_actions.pack(fill="x")
        ttk.Label(alert_actions, text="Acción sobre la alerta seleccionada:",
                  style="Muted.TLabel").pack(side="left")
        ttk.Button(alert_actions, text=" Enviar advertencia", style="Warning.TButton",
                   command=self._warn_from_alert).pack(side="left", padx=(10, 5))
        ttk.Button(alert_actions, text="🔨 Banear usuario", style="Danger.TButton",
                   command=self._ban_from_alert).pack(side="left", padx=5)

        ttk.Label(self.tab_dashboard, text="Usuarios más activos (top 5)",
                  style="Header.TLabel").pack(anchor="w", padx=14, pady=(4, 0))
        self.top_users_var = tk.StringVar(value="")
        ttk.Label(self.tab_dashboard, textvariable=self.top_users_var,
                  style="Muted.TLabel", padding=10).pack(anchor="w", padx=8)

    def _build_events_tab(self):
        filt = ttk.Frame(self.tab_events, padding=12)
        filt.pack(fill="x")

        ttk.Label(filt, text="Tipo:").pack(side="left")
        self.event_type_var = tk.StringVar(value=EVENT_TYPES[0])
        ttk.OptionMenu(filt, self.event_type_var, EVENT_TYPES[0], *EVENT_TYPES,
                       command=lambda _: self._refresh_events()).pack(side="left", padx=5)

        ttk.Label(filt, text="Buscar (usuario o contenido):").pack(side="left", padx=(15, 0))
        self.search_var = tk.StringVar()
        entry = ttk.Entry(filt, textvariable=self.search_var, width=30)
        entry.pack(side="left", padx=5)
        entry.bind("<Return>", lambda e: self._refresh_events())
        ttk.Button(filt, text="Buscar", style="Accent.TButton",
                   command=self._refresh_events).pack(side="left")

        columns = ("timestamp", "event_type", "username", "channel_id", "content")
        headers = ("Fecha/hora", "Tipo", "Usuario", "Canal", "Contenido")
        self.events_tree = ttk.Treeview(self.tab_events, columns=columns, show="headings", height=25)
        for col, head, width in zip(columns, headers, (150, 120, 140, 90, 430)):
            self.events_tree.heading(col, text=head)
            self.events_tree.column(col, width=width, anchor="w")
        self.events_tree.pack(fill="both", expand=True, padx=12, pady=10)
        theme.tag_configure_zebra(self.events_tree)

    def _build_members_tab(self):
        columns = ("username", "joined_at", "account_created_at", "left_at")
        headers = ("Usuario", "Se unió", "Cuenta creada", "Salió")
        self.members_tree = ttk.Treeview(self.tab_members, columns=columns, show="headings", height=28)
        for col, head, width in zip(columns, headers, (160, 180, 180, 180)):
            self.members_tree.heading(col, text=head)
            self.members_tree.column(col, width=width, anchor="w")
        self.members_tree.pack(fill="both", expand=True, padx=12, pady=(12, 0))
        theme.tag_configure_zebra(self.members_tree)
        self.members_tree.tag_configure("left", foreground=theme.TEXT_MUTED)

        actions = ttk.Frame(self.tab_members, padding=(12, 8))
        actions.pack(fill="x")
        ttk.Button(actions, text=" Banear seleccionado", style="Danger.TButton",
                   command=self._ban_selected_member).pack(side="right", padx=(5, 0))
        ttk.Button(actions, text=" Expulsar seleccionado", style="Warning.TButton",
                   command=self._kick_selected_member).pack(side="right", padx=(5, 0))
        ttk.Button(actions, text=" Timeout seleccionado", style="Warning.TButton",
                   command=self._timeout_selected_member).pack(side="right", padx=(5, 0))
        ttk.Button(actions, text=" Avisar seleccionado",
                   command=self._warn_selected_member).pack(side="right", padx=(5, 0))
        ttk.Button(actions, text=" Ver historial",
                   command=self._show_member_history).pack(side="right")

    def _build_rules_tab(self):
        container = ttk.Frame(self.tab_rules, padding=12)
        container.pack(fill="both", expand=True)

        # --- Watched keywords ---
        kw_frame = ttk.LabelFrame(container, text="Palabras vigiladas", padding=12)
        kw_frame.pack(fill="both", expand=True, pady=6)

        form = ttk.Frame(kw_frame)
        form.pack(fill="x")
        ttk.Label(form, text="Palabra:").grid(row=0, column=0, padx=2)
        self.kw_word_var = tk.StringVar()
        ttk.Entry(form, textvariable=self.kw_word_var, width=25).grid(row=0, column=1, padx=5)
        ttk.Label(form, text="Severidad:").grid(row=0, column=2, padx=2)
        self.kw_sev_var = tk.StringVar(value="medium")
        ttk.OptionMenu(form, self.kw_sev_var, "medium", "low", "medium", "high", "critical").grid(
            row=0, column=3, padx=5)
        self.kw_delete_var = tk.BooleanVar()
        ttk.Checkbutton(form, text="Borrar mensaje", variable=self.kw_delete_var).grid(
            row=0, column=4, padx=5)
        ttk.Button(form, text="➕ Añadir", style="Accent.TButton",
                   command=self._add_keyword).grid(row=0, column=5, padx=5)

        self.kw_tree = ttk.Treeview(kw_frame, columns=("id", "word", "severity", "delete"),
                                     show="headings", height=6)
        for col, head, width in zip(("id", "word", "severity", "delete"),
                                     ("ID", "Palabra", "Severidad", "Borra"), (80, 220, 90, 70)):
            self.kw_tree.heading(col, text=head)
            self.kw_tree.column(col, width=width)
        self.kw_tree.pack(fill="both", expand=True, pady=6)
        theme.tag_configure_zebra(self.kw_tree)
        ttk.Button(kw_frame, text="🗑️ Eliminar seleccionada", style="Danger.TButton",
                   command=self._delete_selected_keyword).pack(anchor="e")

        # --- Link detection ---
        link_frame = ttk.LabelFrame(container, text="Detección de links", padding=12)
        link_frame.pack(fill="x", pady=6)

        self.link_enabled_var = tk.BooleanVar()
        ttk.Checkbutton(link_frame, text="Activada", variable=self.link_enabled_var,
                         command=self._toggle_links).pack(side="left")
        ttk.Label(link_frame, text="Severidad:").pack(side="left", padx=(15, 0))
        self.link_sev_var = tk.StringVar(value="low")
        ttk.OptionMenu(link_frame, self.link_sev_var, "low", "low", "medium", "high", "critical",
                       command=lambda _: self._toggle_links()).pack(side="left")

        ttk.Label(link_frame, text="   Añadir a whitelist:").pack(side="left", padx=(15, 0))
        self.whitelist_var = tk.StringVar()
        ttk.Entry(link_frame, textvariable=self.whitelist_var, width=20).pack(side="left", padx=5)
        ttk.Button(link_frame, text="Añadir dominio", style="Accent.TButton",
                   command=self._add_whitelist).pack(side="left")

        self.whitelist_label = ttk.Label(link_frame, text="", style="Muted.TLabel", wraplength=500)
        self.whitelist_label.pack(side="left", padx=10)

        # --- Load rules (flood) ---
        load_frame = ttk.LabelFrame(container, text="Reglas de carga (flood)", padding=12)
        load_frame.pack(fill="both", expand=True, pady=6)

        form2 = ttk.Frame(load_frame)
        form2.pack(fill="x")
        ttk.Label(form2, text="Ámbito:").grid(row=0, column=0, padx=2)
        self.load_scope_var = tk.StringVar(value="user")
        ttk.OptionMenu(form2, self.load_scope_var, "user", "user", "channel").grid(
            row=0, column=1, padx=5)
        ttk.Label(form2, text="Máx mensajes:").grid(row=0, column=2, padx=2)
        self.load_max_var = tk.StringVar(value="6")
        ttk.Entry(form2, textvariable=self.load_max_var, width=6).grid(row=0, column=3, padx=5)
        ttk.Label(form2, text="Ventana (s):").grid(row=0, column=4, padx=2)
        self.load_window_var = tk.StringVar(value="8")
        ttk.Entry(form2, textvariable=self.load_window_var, width=6).grid(row=0, column=5, padx=5)
        ttk.Label(form2, text="Severidad:").grid(row=0, column=6, padx=2)
        self.load_sev_var = tk.StringVar(value="medium")
        ttk.OptionMenu(form2, self.load_sev_var, "medium", "low", "medium", "high", "critical").grid(
            row=0, column=7, padx=5)
        ttk.Button(form2, text="➕ Añadir", style="Accent.TButton",
                   command=self._add_load_rule).grid(row=0, column=8, padx=5)

        self.load_tree = ttk.Treeview(
            load_frame, columns=("id", "scope", "max", "window", "severity"),
            show="headings", height=6)
        for col, head, width in zip(("id", "scope", "max", "window", "severity"),
                                     ("ID", "Ámbito", "Máx", "Ventana", "Severidad"),
                                     (80, 90, 70, 80, 90)):
            self.load_tree.heading(col, text=head)
            self.load_tree.column(col, width=width)
        self.load_tree.pack(fill="both", expand=True, pady=6)
        theme.tag_configure_zebra(self.load_tree)
        ttk.Button(load_frame, text="🗑️ Eliminar seleccionada", style="Danger.TButton",
                   command=self._delete_selected_load).pack(anchor="e")

    # ------------------------------------------------------------------
    # Helper to keep the selection when a Treeview is refreshed
    # ------------------------------------------------------------------
    def _save_selection(self, tree):
        """Returns the 'values' tuple of the currently selected rows."""
        return [tuple(tree.item(i)["values"]) for i in tree.selection()]

    def _restore_selection(self, tree, saved_values):
        """Reselects the rows whose 'values' match the saved ones."""
        if not saved_values:
            return
        for item in tree.get_children():
            if tuple(tree.item(item)["values"]) in saved_values:
                tree.selection_add(item)

    def _build_analytics_tab(self):
        top = ttk.Frame(self.tab_analytics, padding=12)
        top.pack(fill="x")

        self.analytics_title_var = tk.StringVar(value="Alertas por día (últimos 14 días)")
        ttk.Label(top, textvariable=self.analytics_title_var,
                  style="Header.TLabel").pack(side="left")

        ttk.Label(top, text="Rango:").pack(side="left", padx=(20, 4))
        self.analytics_days_var = tk.StringVar(value="14")
        days_combo = ttk.Combobox(top, textvariable=self.analytics_days_var,
                                   values=("7", "14", "30", "90"), width=5, state="readonly")
        days_combo.pack(side="left")
        days_combo.bind("<<ComboboxSelected>>", lambda e: self._refresh_analytics())

        ttk.Button(top, text="🔄 Refrescar", style="Accent.TButton",
                   command=self._refresh_analytics).pack(side="right", padx=4)
        ttk.Button(top, text="⬇️ Exportar eventos CSV",
                   command=self._export_events_csv).pack(side="right", padx=4)
        ttk.Button(top, text="⬇️ Exportar alertas CSV",
                   command=self._export_alerts_csv).pack(side="right", padx=4)

        # --- Embedded chart (matplotlib on top of Tkinter) ---
        chart_frame = ttk.Frame(self.tab_analytics, padding=(12, 0))
        chart_frame.pack(fill="both", expand=True)

        bg_color = getattr(theme, "BG_DARK", getattr(theme, "BG_SECONDARY", "#2b2d31"))
        fig = Figure(figsize=(8, 3.2), dpi=100, facecolor=bg_color)
        self.analytics_fig = fig
        self.analytics_ax = fig.add_subplot(111)
        self.analytics_canvas = FigureCanvasTkAgg(fig, master=chart_frame)
        self.analytics_canvas.get_tk_widget().pack(fill="both", expand=True)

        # --- Rule and user rankings, side by side ---
        tables_frame = ttk.Frame(self.tab_analytics, padding=(12, 10, 12, 12))
        tables_frame.pack(fill="both", expand=True)

        rules_col = ttk.Frame(tables_frame)
        rules_col.pack(side="left", fill="both", expand=True, padx=(0, 6))
        ttk.Label(rules_col, text="Reglas que más alertas generan (top 15)",
                  style="Header.TLabel").pack(anchor="w", pady=(0, 4))
        columns = ("rule_name", "count")
        headers = ("Regla", "Nº de alertas")
        self.ranking_tree = ttk.Treeview(rules_col, columns=columns, show="headings", height=8)
        for col, head, width in zip(columns, headers, (220, 100)):
            self.ranking_tree.heading(col, text=head)
            self.ranking_tree.column(col, width=width, anchor="w")
        self.ranking_tree.pack(fill="both", expand=True)
        theme.tag_configure_zebra(self.ranking_tree)

        users_col = ttk.Frame(tables_frame)
        users_col.pack(side="left", fill="both", expand=True, padx=(6, 0))
        ttk.Label(users_col, text="Usuarios con más alertas (top 15)",
                  style="Header.TLabel").pack(anchor="w", pady=(0, 4))
        columns = ("username", "count")
        headers = ("Usuario", "Nº de alertas")
        self.top_users_tree = ttk.Treeview(users_col, columns=columns, show="headings", height=8)
        for col, head, width in zip(columns, headers, (220, 100)):
            self.top_users_tree.heading(col, text=head)
            self.top_users_tree.column(col, width=width, anchor="w")
        self.top_users_tree.pack(fill="both", expand=True)
        theme.tag_configure_zebra(self.top_users_tree)

    # ------------------------------------------------------------------
    # Data refresh
    # ------------------------------------------------------------------
    def _auto_refresh(self):
        self._refresh_all()
        self.after(REFRESH_MS, self._auto_refresh)

    def _refresh_all(self):
        try:
            self._refresh_dashboard()
            self._refresh_events()
            self._refresh_members()
            self._refresh_rules_view()
            self._refresh_analytics()
            self.status_var.set("Actualizado correctamente.")
        except Exception as e:
            self.status_var.set(f"Error al refrescar: {e}")

    def _refresh_dashboard(self):
        counts = count_alerts_by_severity()
        for sev, lbl in self.stat_labels.items():
            lbl.config(text=str(counts.get(sev, 0)))

        saved = self._save_selection(self.alerts_tree)
        for item in self.alerts_tree.get_children():
            self.alerts_tree.delete(item)
        for idx, a in enumerate(fetch_alerts(limit=200)):
            item_id = self.alerts_tree.insert(
                "", "end",
                values=(a["timestamp"], a["severity"], a["rule_name"],
                        a["username"] or "-", a["description"]),
            )
            # store user_id/guild_id outside the visible columns, so we
            # can ban/warn directly from the alert
            self.alerts_tree.item(
                item_id,
                tags=(a["severity"], theme.zebra_tag(idx),
                      f"uid:{a['user_id']}", f"gid:{a['guild_id']}")
            )
        self._restore_selection(self.alerts_tree, saved)

        top = top_active_users(5)
        if top:
            self.top_users_var.set(
                "  |  ".join(f"{u['username']} ({u['n']} msgs)" for u in top)
            )
        else:
            self.top_users_var.set("Sin datos todavía.")

    def _refresh_events(self):
        etype = self.event_type_var.get()
        etype = None if etype == "todos" else etype
        search = self.search_var.get().strip() or None

        saved = self._save_selection(self.events_tree)
        for item in self.events_tree.get_children():
            self.events_tree.delete(item)
        for idx, e in enumerate(fetch_events(limit=300, event_type=etype, search=search)):
            self.events_tree.insert(
                "", "end",
                values=(e["timestamp"], e["event_type"], e["username"] or "-",
                        e["channel_id"] or "-", (e["content"] or "")[:200]),
                tags=(theme.zebra_tag(idx),)
            )
        self._restore_selection(self.events_tree, saved)

    def _refresh_members(self):
        saved = self._save_selection(self.members_tree)
        for item in self.members_tree.get_children():
            self.members_tree.delete(item)
        for idx, m in enumerate(fetch_members()):
            tag = "left" if m["left_at"] else ""
            item_id = self.members_tree.insert(
                "", "end",
                values=(m["username"], m["joined_at"] or "-",
                        m["account_created_at"] or "-", m["left_at"] or ""),
            )
            # store user_id/guild_id outside the visible columns, so we
            # can kick/ban/warn the right member
            self.members_tree.item(
                item_id,
                tags=(tag, theme.zebra_tag(idx), f"uid:{m['user_id']}", f"gid:{m['guild_id']}")
            )
        self._restore_selection(self.members_tree, saved)

    def _refresh_rules_view(self):
        self.rule_engine.reload()

        saved_kw = self._save_selection(self.kw_tree)
        for item in self.kw_tree.get_children():
            self.kw_tree.delete(item)
        for idx, r in enumerate(self.rule_engine.list_keywords()):
            self.kw_tree.insert("", "end", values=(
                r["id"], r["word"], r["severity"], "sí" if r["delete_message"] else "no"),
                tags=(theme.zebra_tag(idx),))
        self._restore_selection(self.kw_tree, saved_kw)

        ld = self.rule_engine.rules["link_detection"]
        self.link_enabled_var.set(ld["enabled"])
        self.link_sev_var.set(ld["severity"])
        self.whitelist_label.config(text="Whitelist: " + (", ".join(ld["whitelist_domains"]) or "(vacía)"))

        saved_load = self._save_selection(self.load_tree)
        for item in self.load_tree.get_children():
            self.load_tree.delete(item)
        for idx, r in enumerate(self.rule_engine.list_load_rules()):
            self.load_tree.insert("", "end", values=(
                r["id"], r["scope"], r["max_messages"], r["window_seconds"], r["severity"]),
                tags=(theme.zebra_tag(idx),))
        self._restore_selection(self.load_tree, saved_load)

    def _refresh_analytics(self):
        # --- Stacked chart of alerts per day and severity ---
        data = fetch_alerts_by_day(days=14)
        days = sorted({d["day"] for d in data})
        severities = ("low", "medium", "high", "critical")

        bg_color = getattr(theme, "BG_DARK", getattr(theme, "BG_SECONDARY", "#2b2d31"))
        text_color = getattr(theme, "TEXT_MUTED", "#b5bac1")

        self.analytics_ax.clear()
        self.analytics_ax.set_facecolor(bg_color)

        if days:
            bottoms = [0] * len(days)
            for sev in severities:
                counts = [
                    next((d["n"] for d in data if d["day"] == day and d["severity"] == sev), 0)
                    for day in days
                ]
                color = theme.SEVERITY_COLORS.get(sev, "#888888")
                self.analytics_ax.bar(days, counts, bottom=bottoms, label=sev, color=color)
                bottoms = [b + c for b, c in zip(bottoms, counts)]

            legend = self.analytics_ax.legend(fontsize=8, facecolor=bg_color)
            for text in legend.get_texts():
                text.set_color(text_color)
            self.analytics_ax.tick_params(axis="x", colors=text_color, rotation=45, labelsize=7)
            self.analytics_ax.tick_params(axis="y", colors=text_color, labelsize=8)
            for spine in self.analytics_ax.spines.values():
                spine.set_color(text_color)
        else:
            self.analytics_ax.text(
                0.5, 0.5, "Sin alertas en los últimos 14 días",
                ha="center", va="center", color=text_color,
                transform=self.analytics_ax.transAxes
            )
            self.analytics_ax.set_xticks([])
            self.analytics_ax.set_yticks([])

        self.analytics_fig.tight_layout()
        self.analytics_canvas.draw()

        # --- Rule ranking ---
        saved = self._save_selection(self.ranking_tree)
        for item in self.ranking_tree.get_children():
            self.ranking_tree.delete(item)
        for idx, r in enumerate(fetch_rule_ranking(limit=15)):
            self.ranking_tree.insert(
                "", "end", values=(r["rule_name"], r["n"]),
                tags=(theme.zebra_tag(idx),)
            )
        self._restore_selection(self.ranking_tree, saved)

    def _export_alerts_csv(self):
        path = filedialog.asksaveasfilename(
            title="Exportar alertas a CSV", defaultextension=".csv",
            filetypes=[("CSV", "*.csv")], initialfile="alertas_edr.csv")
        if not path:
            return  # el usuario canceló el diálogo

        alerts = fetch_alerts(limit=100000)
        if not alerts:
            messagebox.showinfo("Aviso", "No hay alertas que exportar.")
            return

        try:
            # utf-8-sig so Excel on Windows correctly detects accents/emoji
            with open(path, "w", newline="", encoding="utf-8-sig") as f:
                writer = csv.DictWriter(f, fieldnames=list(alerts[0].keys()))
                writer.writeheader()
                writer.writerows(alerts)
            self.status_var.set(f"{len(alerts)} alertas exportadas a {path}")
        except Exception as e:
            messagebox.showerror("Error", f"No se pudo exportar el CSV: {e}")

    def _export_events_csv(self):
        path = filedialog.asksaveasfilename(
            title="Exportar eventos a CSV", defaultextension=".csv",
            filetypes=[("CSV", "*.csv")], initialfile="eventos_edr.csv")
        if not path:
            return  # el usuario canceló el diálogo

        events = fetch_events(limit=100000)
        if not events:
            messagebox.showinfo("Aviso", "No hay eventos que exportar.")
            return

        try:
            with open(path, "w", newline="", encoding="utf-8-sig") as f:
                writer = csv.DictWriter(f, fieldnames=list(events[0].keys()))
                writer.writeheader()
                writer.writerows(events)
            self.status_var.set(f"{len(events)} eventos exportados a {path}")
        except Exception as e:
            messagebox.showerror("Error", f"No se pudo exportar el CSV: {e}")

    # ------------------------------------------------------------------
    # Moderation actions from a selected alert (Dashboard tab)
    # ------------------------------------------------------------------
    def _get_selected_alert_info(self):
        """Returns (username, user_id, guild_id, description) for the
        selected alert, or None if nothing is selected or the involved
        user/server can't be identified (e.g. old alerts missing that data)."""
        sel = self.alerts_tree.selection()
        if not sel:
            messagebox.showinfo("Aviso", "Selecciona primero una alerta en la lista.")
            return None

        item = self.alerts_tree.item(sel[0])
        username = item["values"][3]
        description = item["values"][4]
        tags = item["tags"]
        user_id = next((t.split(":", 1)[1] for t in tags if t.startswith("uid:")), None)
        guild_id = next((t.split(":", 1)[1] for t in tags if t.startswith("gid:")), None)

        if not user_id or user_id == "None" or not guild_id or guild_id == "None":
            messagebox.showerror(
                "Error",
                "Esta alerta no tiene un usuario o servidor asociado con el que actuar."
            )
            return None
        return username, user_id, guild_id, description

    def _warn_from_alert(self):
        info = self._get_selected_alert_info()
        if not info:
            return
        username, user_id, guild_id, description = info

        reason = simpledialog.askstring(
            "Motivo del aviso", f"¿Qué quieres decirle a {username}?",
            initialvalue=description, parent=self)
        if reason is None:
            return  # el usuario canceló el diálogo

        queue_action("warn", guild_id, user_id, reason=reason, username=username)
        self.status_var.set(f"Aviso a {username} solicitado. Se enviará en unos segundos.")

    def _ban_from_alert(self):
        info = self._get_selected_alert_info()
        if not info:
            return
        username, user_id, guild_id, description = info

        if not messagebox.askyesno(
                "Confirmar baneo",
                f"¿Seguro que quieres banear a {username} del servidor?\n"
                f"Esta acción es severa: el usuario no podrá volver a entrar."):
            return

        reason = simpledialog.askstring(
            "Motivo del baneo", "Motivo:", initialvalue=description, parent=self)

        queue_action("ban", guild_id, user_id, reason=reason, username=username)
        self.status_var.set(f"Baneo de {username} solicitado. Se ejecutará en unos segundos.")

    # ------------------------------------------------------------------
    # Moderation actions from a selected member (Members tab)
    # ------------------------------------------------------------------
    def _get_selected_member_info(self):
        """Returns (username, user_id, guild_id, left_at) for the selected member, or None."""
        sel = self.members_tree.selection()
        if not sel:
            messagebox.showinfo("Aviso", "Selecciona primero un miembro en la lista.")
            return None

        item = self.members_tree.item(sel[0])
        username = item["values"][0]
        left_at = item["values"][3]
        tags = item["tags"]
        user_id = next((t.split(":", 1)[1] for t in tags if t.startswith("uid:")), None)
        guild_id = next((t.split(":", 1)[1] for t in tags if t.startswith("gid:")), None)
        if not user_id or not guild_id:
            messagebox.showerror("Error", "No se pudo identificar al usuario.")
            return None
        return username, user_id, guild_id, left_at

    def _kick_selected_member(self):
        info = self._get_selected_member_info()
        if not info:
            return
        username, user_id, guild_id, left_at = info
        if left_at:
            messagebox.showinfo("Aviso", f"{username} ya no está en el servidor.")
            return

        if not messagebox.askyesno("Confirmar expulsión",
                                    f"¿Seguro que quieres expulsar a {username} del servidor?"):
            return

        reason = simpledialog.askstring("Motivo (opcional)",
                                         "Motivo de la expulsión:", parent=self)

        queue_action("kick", guild_id, user_id, reason=reason, username=username)
        self.status_var.set(f"Expulsión de {username} solicitada. Se ejecutará en unos segundos.")

    def _warn_selected_member(self):
        info = self._get_selected_member_info()
        if not info:
            return
        username, user_id, guild_id, left_at = info
        if left_at:
            messagebox.showinfo("Aviso", f"{username} ya no está en el servidor.")
            return

        reason = simpledialog.askstring("Motivo del aviso",
                                         f"¿Por qué avisas a {username}?", parent=self)
        if reason is None:
            return  # el usuario canceló el diálogo

        queue_action("warn", guild_id, user_id, reason=reason, username=username)
        self.status_var.set(f"Aviso a {username} solicitado. Se enviará en unos segundos.")

    def _timeout_selected_member(self):
        info = self._get_selected_member_info()
        if not info:
            return
        username, user_id, guild_id, left_at = info
        if left_at:
            messagebox.showinfo("Aviso", f"{username} ya no está en el servidor.")
            return

        minutes = simpledialog.askinteger(
            "Duración del timeout",
            f"¿Cuántos minutos quieres silenciar a {username}?",
            initialvalue=10, minvalue=1, maxvalue=40320,  # 40320 min = 28 días, límite de Discord
            parent=self)
        if minutes is None:
            return  # el usuario canceló el diálogo

        reason = simpledialog.askstring("Motivo (opcional)",
                                         "Motivo del timeout:", parent=self)

        queue_action("timeout", guild_id, user_id, reason=reason,
                     username=username, duration_seconds=minutes * 60)
        self.status_var.set(f"Timeout de {minutes} min para {username} solicitado.")

    def _show_member_history(self):
        info = self._get_selected_member_info()
        if not info:
            return
        username, user_id, guild_id, left_at = info

        win = tk.Toplevel(self)
        win.title(f"Historial de moderación — {username}")
        win.geometry("680x360")
        theme.apply_theme(win)

        columns = ("requested_at", "action_type", "duration", "status", "reason")
        headers = ("Fecha", "Acción", "Duración", "Estado", "Motivo")
        tree = ttk.Treeview(win, columns=columns, show="headings", height=14)
        for col, head, width in zip(columns, headers, (150, 90, 80, 80, 260)):
            tree.heading(col, text=head)
            tree.column(col, width=width, anchor="w")
        tree.pack(fill="both", expand=True, padx=10, pady=10)
        theme.tag_configure_zebra(tree)

        actions = fetch_actions_for_user(user_id, limit=50)
        if not actions:
            ttk.Label(win, text="Sin acciones registradas para este usuario.",
                      style="Muted.TLabel").pack(pady=(0, 10))
            return

        for idx, a in enumerate(actions):
            duration = f"{a['duration_seconds'] // 60} min" if a.get("duration_seconds") else "-"
            tree.insert(
                "", "end",
                values=(a["requested_at"], a["action_type"], duration,
                        a["status"], a["reason"] or "-"),
                tags=(theme.zebra_tag(idx),)
            )

    def _ban_selected_member(self):
        info = self._get_selected_member_info()
        if not info:
            return
        username, user_id, guild_id, left_at = info

        if not messagebox.askyesno(
                "Confirmar baneo",
                f"¿Seguro que quieres banear a {username} del servidor?\n"
                f"Esta acción es más severa que expulsar: el usuario no podrá volver a entrar."):
            return

        reason = simpledialog.askstring("Motivo (opcional)",
                                         "Motivo del baneo:", parent=self)

        queue_action("ban", guild_id, user_id, reason=reason, username=username)
        self.status_var.set(f"Baneo de {username} solicitado. Se ejecutará en unos segundos.")

    # ------------------------------------------------------------------
    # Rule actions
    # ------------------------------------------------------------------
    def _add_keyword(self):
        word = self.kw_word_var.get().strip()
        if not word:
            messagebox.showwarning("Aviso", "Escribe una palabra antes de añadir la regla.")
            return
        self.rule_engine.add_keyword(word, severity=self.kw_sev_var.get(),
                                      delete_message=self.kw_delete_var.get())
        self.kw_word_var.set("")
        self.kw_delete_var.set(False)
        self._refresh_rules_view()
        self.status_var.set(f"Palabra vigilada '{word}' añadida.")

    def _delete_selected_keyword(self):
        sel = self.kw_tree.selection()
        if not sel:
            return
        rule_id = self.kw_tree.item(sel[0])["values"][0]
        self.rule_engine.remove_keyword(rule_id)
        self._refresh_rules_view()

    def _toggle_links(self):
        self.rule_engine.set_link_detection(
            enabled=self.link_enabled_var.get(), severity=self.link_sev_var.get())
        self.status_var.set("Detección de links actualizada.")

    def _add_whitelist(self):
        domain = self.whitelist_var.get().strip()
        if not domain:
            return
        self.rule_engine.add_whitelist_domain(domain)
        self.whitelist_var.set("")
        self._refresh_rules_view()

    def _add_load_rule(self):
        try:
            max_msgs = int(self.load_max_var.get())
            window = int(self.load_window_var.get())
        except ValueError:
            messagebox.showerror("Error", "Máx. mensajes y ventana deben ser números enteros.")
            return
        self.rule_engine.add_load_rule(
            self.load_scope_var.get(), max_msgs, window, severity=self.load_sev_var.get())
        self._refresh_rules_view()
        self.status_var.set("Regla de carga añadida.")

    def _delete_selected_load(self):
        sel = self.load_tree.selection()
        if not sel:
            return
        rule_id = self.load_tree.item(sel[0])["values"][0]
        self.rule_engine.remove_load_rule(rule_id)
        self._refresh_rules_view()


def main():
    app = EDRDesktopApp()
    app.mainloop()


if __name__ == "__main__":
    main()